### ISSUE TITLE
Slack: No account found

### ISSUE THREAD

**Issue by BruciiZ** [datasciencelabs/2024#1]
Hi Prof. Irizarry,

Hope this issue finds you well. I clicked on "https://bst260fall2024.slack.com/" and entered my school email which ends with "@hsph.harvard.edu". I tried several times and every time I got an email saying that:

_**"Is this the right email? It looks like there isn’t an account on BST 260 Fall 2024 tied to this email address. You can always try again with a different email, or [find workspaces associated with this email]"**_

Am I supposed to use a different email? Thank you in advance for your attention to this.

Best,
Bruce

**Comment by nikhil-vytla** [comment]
Hello Bruce,

Please complete the BST 260 Opening Survey, linked in [this Canvas announcement](https://canvas.harvard.edu/courses/143922/discussion_topics/1067300). This survey is required for all students to complete, and should provide you with access to Slack.
